/* 
 * File:   Convert.h
 * Author: colman
 *
 * Created on June 14, 2015, 4:46 AM
 */

#ifndef CONFIGURATION_H
#define	CONFIGURATION_H

// Localization Manager
#define LOW_BELIF_THRESHOLD 0.2
#define HIGH_BELIF_THRESHOLD 0.7
#define PARTICLE_NORMAL_BREED 2
#define PARTICLE_HIGH_BREED 5
#define MAX_PARTICLES_COUNT 15
#define PARTICLE_EMERGENCY_BREED MAX_PARTICLES_COUNT - 2

// Particle
#define EXPANSION_RADIUS 0.3
#define EMERGENCY_EXPANSION_RADIUS 5
#define BELIF_MAGIC_NUMBER 2
#define PARTICLE_LIFES 5

// Waypoint Manager
#define WAYPOINT_RADIUS 2
#define DEFAULT_WAYPOINT_RESOLUTION 4
#define DEFAULT_WAYPOINT_ACCURACY (0.1F)
#define DETECT_EVASION_RADIUS 0.75

#endif	/* CONFIGURATION_H */

